import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/settings_provider.dart';

const Map<String, Map<String, String>> _localizedValues = {
  'th': {
    'settings': 'ตั้งค่า',
    'display': 'การแสดงผล',
    'dark_mode': 'โหมดมืด',
    'keep_screen_awake': 'เปิดหน้าจอค้างไว้',
    'keep_screen_awake_desc': 'ป้องกันไม่ให้หน้าจอดับขณะอ่าน',
    'reading_experience': 'ประสบการณ์การอ่าน',
    'reading_mode': 'โหมดการอ่าน',
    'font_sizes': 'ขนาดตัวอักษร',
    'arabic_font_size': 'ขนาดอักษรอารบิก',
    'translation_font_size': 'ขนาดอักษรแปลภาษา',
    'translation_settings': 'ตั้งค่าบทแปล',
    'primary_translation': 'บทแปลหลัก',
    'secondary_translation': 'บทแปลรอง',
    'primary': 'หลัก',
    'secondary': 'รอง',
    'active_translations': 'บทแปลที่เปิดใช้งาน',
    'translations': 'บทแปล',
    'theme_settings': 'ตั้งค่าธีม',
    'theme_color': 'สีของธีม',
    'system_settings': 'ตั้งค่าระบบ',
    'web_host_url': 'URL โฮสต์เว็บ',
    'language': 'ภาษา (Language)',
    'salam': 'สลาม',
    'which_surah_to_read': 'คุณต้องการอ่านสูเราะฮ์ไหน?',
    'home_search_hint': 'ค้นหา สูเราะฮ์, หน้า, หรือความหมาย...',
    'continue_your_last_read': 'อ่านต่อจากครั้งล่าสุด',
    'weekday_mon_short': 'จ',
    'weekday_tue_short': 'อ',
    'weekday_wed_short': 'พ',
    'weekday_thu_short': 'พฤ',
    'weekday_fri_short': 'ศ',
    'weekday_sat_short': 'ส',
    'weekday_sun_short': 'อา',
    'just_read': 'อ่านเลย',
    'continue_reading': 'อ่านต่อ',
    'resume_progress': 'อ่านต่อเป้าหมาย',
    'save_progress': 'บันทึกความคืบหน้า',
    'next_ayah': 'ถัดไป',
    'previous_ayah': 'ก่อน',
    'next_unread_verse': 'อายะฮ์ถัดไป',
    'next_unread_page': 'หน้าถัดไป',
    'last_viewed': 'ดูล่าสุด',
    'jump_back': 'กลับไปดู',
    'select_reading_mode': 'เลือกรูปแบบการอ่าน',
    'verse_by_verse': 'อ่านรายอายะฮ์',
    'translation_audio': 'บทแปลและเสียงอ่าน',
    'mushaf_page': 'หน้ามุสฮัฟ',
    'free_read': 'อ่านอิสระ',
    'quick_links': 'ทางลัด',
    'meaningful_read': 'อ่านเพื่อใคร่ครวญ',
    'mushaf_read': 'อ่านจากหน้ามุสฮัฟ',
    'tadabbur': 'บันทึกตะดับบุร',
    'current_ayah': 'อายะห์ปัจจุบัน',
    'add_goal': 'เพิ่มเป้าหมาย',
    'delete_goal': 'ลบเป้าหมาย',
    'display_settings': 'ตั้งค่าการแสดงผล',
    'mushaf_settings': 'ตั้งค่ามุสฮัฟ',
    'current_profile': 'โปรไฟล์ปัจจุบัน',
    'see_all': 'ดูทั้งหมด',
    'mushaf_font_layout': 'ฟอนต์และรูปแบบมุสฮัฟ',
    'current_view': 'มุมมองปัจจุบัน: {name} • หน้า {page}',
    'optimize_brightness': 'ปรับความสว่างหน้าจอให้เหมาะกับการอ่าน',
    'add_note_title': 'เพิ่มบันทึก?',
    'favorite_add_note_prompt':
        'บันทึกอายะฮ์เป็นรายการโปรดแล้ว ต้องการเพิ่มบันทึกตอนนี้ไหม?',
    'later': 'ภายหลัง',
    'add_note': 'เพิ่มบันทึก',
    'tap_ayah_first': 'แตะอายะฮ์ก่อนเพื่อบันทึกเป็นรายการโปรด',
    'verse_saved_favorite': 'บันทึกอายะฮ์เป็นรายการโปรดแล้ว',
    'removed_from_favorites': 'ลบออกจากรายการโปรดแล้ว',
    'remove_favorite_title': 'ลบรายการโปรด?',
    'remove_favorite_with_note':
        'อายะฮ์นี้มีบันทึกอยู่ การลบรายการโปรดจะลบบันทึกนี้ด้วย',
    'remove': 'ลบออก',
    'failed_to_delete': 'ลบไม่สำเร็จ: {error}',
    'failed_to_update': 'อัปเดตไม่สำเร็จ: {error}',
    'no_reflections_yet': 'ยังไม่มีบันทึกตะดับบุร',
    'add_reflections_while_reading': 'เพิ่มบันทึกตะดับบุรระหว่างอ่านอัลกุรอาน',
    'surahs': 'สูเราะฮ์',
    'all': 'ทั้งหมด',
    'notes_count_short': '{count} บันทึก',
    'favorited_no_reflection':
        'บันทึกอายะฮ์นี้เป็นรายการโปรดแล้ว (ยังไม่มีข้อความตะดับบุร)',
    'edit': 'แก้ไข',
    'unfavorite': 'ยกเลิกรายการโปรด',
    'remove_from_favorites': 'ลบออกจากรายการโปรด',
    'unfavorite_confirm': 'คุณต้องการยกเลิกรายการโปรดอายะฮ์นี้หรือไม่?',
    'login_to_like': 'กรุณาเข้าสู่ระบบเพื่อกดถูกใจบันทึกตะดับบุร',
    'login_to_share': 'กรุณาเข้าสู่ระบบเพื่อแชร์บันทึกตะดับบุร',
    'failed_to_like': 'กดถูกใจไม่สำเร็จ: {error}',
    'failed_to_post': 'โพสต์ไม่สำเร็จ: {error}',
    'global_insights': 'ข้อคิดจากชุมชน',
    'all_surahs_filter': 'ทุกสูเราะฮ์',
    'clear_filter': 'ล้างตัวกรอง',
    'share_reflection_heading': 'แชร์บันทึกตะดับบุร',
    'translation_preview': 'ตัวอย่างบทแปล ({reference})',
    'reflection_hint': 'คุณได้เรียนรู้หรือใคร่ครวญอะไรจากอายะฮ์นี้...',
    'post_anonymously': 'โพสต์แบบไม่ระบุตัวตน',
    'share_reflection': 'แชร์บันทึก',
    'first_to_share_reflection': 'เป็นคนแรกที่แชร์บันทึกตะดับบุร',
    'anonymous': 'ไม่ระบุตัวตน',
    'reader': 'ผู้อ่าน',
    'read_in_mushaf': 'อ่านในมุสฮัฟ',
    'translation': 'บทแปล',
    'reset': 'รีเซ็ต',
    'save': 'บันทึก',
    'saving': 'กำลังบันทึก...',
    'cancel': 'ยกเลิก',
    'search_hint': 'ค้นหา สูเราะฮ์, ยุซ, หน้า, หรือคำแปล...',
    'no_results': 'ไม่พบผลลัพธ์การค้นหา',
    'juz': 'ยุซ',
    'page': 'หน้า',
    'start_page': 'หน้าเริ่มต้น',
    'target_page': 'หน้าสิ้นสุด',
    'surah': 'สูเราะฮ์',
    'ayah': 'อายะฮ์',
    'ayah_matches': 'ผลลัพธ์อายะห์',
    'welcome_bismillah':
        'ด้วยพระนามของอัลลอฮฺ\nผู้ทรงกรุณาปรานี ผู้ทรงเมตตาเสมอ',
    'welcome_app_name': 'อ่านอัลกุรอาน',
    'bookmarks': 'บุ๊กมาร์ก',
    'no_bookmarks': 'ไม่มีบุ๊กมาร์ก',
    'my_tadabbur': 'บันทึกตะดับบุรของฉัน',
    'community_tadabbur': 'บันทึกตะดับบุรสาธารณะ',
    'all_surahs': 'สูเราะฮ์ทั้งหมด',
    'all_ayahs': 'อายะห์ทั้งหมด',
    'write_tadabbur': 'เขียนบันทึกตะดับบุร...',
    'share': 'แชร์',
    'public': 'สาธารณะ',
    'private': 'ส่วนตัว',
    'goal_mode': 'โหมดเป้าหมาย',
    'start_surah': 'สูเราะฮ์เริ่มต้น',
    'start_ayah': 'อายะห์เริ่มต้น',
    'target_surah': 'สูเราะฮ์เป้าหมาย',
    'target_ayah': 'อายะห์เป้าหมาย',
    'start_juz': 'ยุซเริ่มต้น',
    'target_juz': 'ยุซเป้าหมาย',
    'goal_title': 'ตั้งเป้าหมายการอ่าน',
    'goal_completed': 'ยินดีด้วย! คุณบรรลุเป้าหมายแล้ว',
    'daily_streak': 'ความต่อเนื่องในการอ่านรายวัน',
    'streak_count': 'ต่อเนื่อง {days} วัน',
    'profile': 'โปรไฟล์',
    'sign_in': 'เข้าสู่ระบบ',
    'sign_out': 'ออกจากระบบ',
    'email': 'อีเมล',
    'password': 'รหัสผ่าน',
    'no_notes': 'ไม่มีบันทึกสำหรับสูเราะฮ์นี้',
    'quran_only': 'อารบิกอย่างเดียว',
    'translation_only': 'คำแปลอย่างเดียว',
    'quran_translation': 'อารบิกและคำแปล',
    'choose_surah': 'เลือกสูเราะฮ์',
    'delete_confirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบสิ่งนี้?',
    'yes': 'ใช่',
    'no': 'ไม่',
    'delete': 'ลบ',
    'completed_ayats': 'อายะห์ที่อ่านแล้ว',
    'total_progress': 'ความคืบหน้าทั้งหมด',
    'juz_mode': 'รายยุซ (By Juz)',
    'surah_mode': 'รายสูเราะฮ์ (By Surah)',
    'ayah_mode': 'รายอายะห์ (By Ayah)',
    'custom_mode': 'กำหนดเอง (Custom)',
    'mushaf_meaningful_desc': 'ใคร่ครวญไตร่ตรองทีละอายะห์ อินชาอัลลอฮฺ',
    'mushaf_read_desc':
        'เติมเต็มความรู้สึกเหมือนอ่านกุรอานจากมุสฮัฟ อินชาอัลลอฮฺ',
    'delete_goal_title': 'ลบแผนการอ่าน?',
    'delete_goal_confirm': 'คุณต้องการลบแผนการอ่านนี้หรือไม่?',
    'all_notes': 'ทั้งหมด',
    'notes_count': '({count} บันทึก)',
    'qcf_v1': 'QCF V1 (มุสฮัฟมาตรฐาน)',
    'qcf_v2': 'QCF V2 (มุสฮัฟขยาย)',
    'thai_v3': 'สมาคมศิษย์เก่าอาหรับ (ถอดความโดยละเอียด)',
    'thai_v2': 'แปลไทยฉบับเก่า',
    'english': 'แปลอังกฤษ (Sahih International)',
    'qcf_tajweed': 'QCF Tajweed V4',
    'qcf_package': 'QCF Package',
    'download_more': 'ดาวน์โหลดเพิ่มเติม',
    'at_least_one_active': 'ต้องเปิดใช้งานอย่างน้อยหนึ่งบทแปล',
    'reading_progress': 'ความคืบหน้าการอ่านของคุณ',
    'see_more': 'ดูเพิ่มเติม',
    'recent_verse': 'อ่านล่าสุด (รายอายะห์)',
    'recent_mushaf': 'อ่านล่าสุด (หน้ามุสฮัฟ)',
    'saved_verses': 'อายะห์ที่บันทึกไว้',
    'saved_mushaf': 'หน้ามุสฮัฟที่บันทึกไว้',
    'no_saved_verses': 'ยังไม่มีอายะห์ที่บันทึกไว้',
    'ayah_number': 'อายะฮ์ที่ {number}',
    'surah_number': 'สูเราะฮ์ {number}',
    'ayat_count': '{count} อายะฮ์',
    'no_results_for': 'ไม่พบผลลัพธ์สำหรับ "{query}"',
    'create_goal': 'สร้างเป้าหมายการอ่าน',
    'edit_goal': 'แก้ไขเป้าหมายการอ่าน',
    'goal_name': 'ชื่อเป้าหมาย',
    'plan_type': 'ประเภทแผน',
    'reset_progress': 'รีเซ็ตความคืบหน้ากลับสู่เริ่มต้น',
    'goal_progress_reset': 'รีเซ็ตความคืบหน้าของเป้าหมายแล้ว',
    'enter_goal_name': 'กรุณากรอกชื่อเป้าหมายก่อน',
    'goal': 'เป้าหมาย',
    'switch_home_tab_create_goal':
        'กรุณาสลับไปยังแท็บหน้าแรกเพื่อสร้างเป้าหมาย',
    'please_enter_goal_name': 'กรุณากรอกชื่อเป้าหมายก่อน',
    'juz_count': '{count} ยุซ',
    'page_count': '{count} หน้า',
    'create': 'สร้าง',
    'end_must_be_after_start': 'ตำแหน่งสิ้นสุดต้องอยู่หลังตำแหน่งเริ่มต้น',
    'edit_name': 'แก้ไขชื่อ',
    'name': 'ชื่อ',
    'please_enter_name': 'กรุณากรอกชื่อ',
    'name_updated_successfully': 'อัปเดตชื่อสำเร็จ',
    'error_occurred': 'เกิดข้อผิดพลาด: {error}',
  },
  'en': {
    'settings': 'Settings',
    'display': 'Display',
    'dark_mode': 'Dark Mode',
    'keep_screen_awake': 'Keep Screen Awake',
    'keep_screen_awake_desc':
        'Prevents the screen from sleeping while reading.',
    'reading_experience': 'Reading Experience',
    'reading_mode': 'Reading Mode',
    'font_sizes': 'Font Sizes',
    'arabic_font_size': 'Arabic Font Size',
    'translation_font_size': 'Translation Font Size',
    'translation_settings': 'Translation Settings',
    'primary_translation': 'Primary Translation',
    'secondary_translation': 'Secondary Translation',
    'primary': 'Primary',
    'secondary': 'Secondary',
    'active_translations': 'Active Translations',
    'translations': 'Translations',
    'theme_settings': 'Theme Settings',
    'theme_color': 'Theme Color',
    'system_settings': 'System Settings',
    'web_host_url': 'Web Host URL',
    'language': 'Language',
    'salam': 'Salam',
    'which_surah_to_read': 'Which surah you want to read?',
    'home_search_hint': 'Search Surah, Page, Meaning...',
    'continue_your_last_read': 'Continue your last read',
    'weekday_mon_short': 'M',
    'weekday_tue_short': 'T',
    'weekday_wed_short': 'W',
    'weekday_thu_short': 'T',
    'weekday_fri_short': 'F',
    'weekday_sat_short': 'S',
    'weekday_sun_short': 'S',
    'just_read': 'Just Read',
    'continue_reading': 'Continue Reading',
    'resume_progress': 'Resume Progress',
    'save_progress': 'Save Progress',
    'next_ayah': 'Next',
    'previous_ayah': 'Previous',
    'next_unread_verse': 'Next Unread Verse',
    'next_unread_page': 'Next Unread Page',
    'last_viewed': 'Last viewed',
    'jump_back': 'Jump Back',
    'select_reading_mode': 'Select Reading Mode',
    'verse_by_verse': 'Verse-by-Verse',
    'translation_audio': 'Translation & Audio',
    'mushaf_page': 'Mushaf Page',
    'free_read': 'Free Read',
    'quick_links': 'Quick Links',
    'meaningful_read': 'Meaningful Read',
    'mushaf_read': 'Mushaf Read',
    'tadabbur': 'Reflections',
    'current_ayah': 'Current ayah',
    'add_goal': 'Add Goal',
    'delete_goal': 'Delete Goal',
    'display_settings': 'Display Settings',
    'mushaf_settings': 'Mushaf Settings',
    'current_profile': 'Current Profile',
    'see_all': 'See all',
    'mushaf_font_layout': 'Mushaf Font & Layout',
    'current_view': 'Current view: {name} • Page {page}',
    'optimize_brightness': 'Optimize screen brightness for reading',
    'add_note_title': 'Add note?',
    'favorite_add_note_prompt':
        'Verse saved as favorite. Do you want to add a note now?',
    'later': 'Later',
    'add_note': 'Add note',
    'tap_ayah_first': 'Tap an ayah first to favorite it.',
    'verse_saved_favorite': 'Verse saved as favorite',
    'removed_from_favorites': 'Removed from favorites',
    'remove_favorite_title': 'Remove favorite?',
    'remove_favorite_with_note':
        'This verse has a note. Removing it will delete the saved note too.',
    'remove': 'Remove',
    'failed_to_delete': 'Failed to delete: {error}',
    'failed_to_update': 'Failed to update: {error}',
    'no_reflections_yet': 'No reflections yet',
    'add_reflections_while_reading': 'Add reflections while reading the Quran.',
    'surahs': 'Surahs',
    'all': 'All',
    'notes_count_short': '{count} notes',
    'favorited_no_reflection':
        'Favorited this verse (no reflection text added)',
    'edit': 'Edit',
    'unfavorite': 'Unfavorite',
    'remove_from_favorites': 'Remove from Favorites',
    'unfavorite_confirm': 'Are you sure you want to unfavorite this verse?',
    'login_to_like': 'Please log in to like reflections.',
    'login_to_share': 'Please log in to share reflections.',
    'failed_to_like': 'Failed to like: {error}',
    'failed_to_post': 'Failed to post: {error}',
    'global_insights': 'Global Insights',
    'all_surahs_filter': 'All Surahs',
    'clear_filter': 'Clear filter',
    'share_reflection_heading': 'Share a Reflection',
    'translation_preview': 'Translation Preview ({reference})',
    'reflection_hint': 'What did you learn or reflect on from this Ayah?...',
    'post_anonymously': 'Post anonymously',
    'share_reflection': 'Share Reflection',
    'first_to_share_reflection': 'Be the first to share your reflection!',
    'anonymous': 'Anonymous',
    'reader': 'Reader',
    'read_in_mushaf': 'Read in Mushaf',
    'translation': 'Translation',
    'reset': 'Reset',
    'save': 'Save',
    'saving': 'Saving...',
    'cancel': 'Cancel',
    'search_hint': 'Search Surah, Juz, Page, Meaning...',
    'no_results': 'No results found',
    'juz': 'Juz',
    'page': 'Page',
    'start_page': 'Start page',
    'target_page': 'Target page',
    'surah': 'Surah',
    'ayah': 'Ayah',
    'ayah_matches': 'Ayah matches',
    'welcome_bismillah':
        'In the name of Allah, the Entirely Merciful, the Especially Merciful',
    'welcome_app_name': 'Quran Reader',
    'bookmarks': 'Bookmarks',
    'no_bookmarks': 'No Bookmarks',
    'my_tadabbur': 'My Reflections',
    'community_tadabbur': 'Community Reflections',
    'all_surahs': 'All Surahs',
    'all_ayahs': 'All',
    'write_tadabbur': 'Write your reflection...',
    'share': 'Share',
    'public': 'Public',
    'private': 'Private',
    'goal_mode': 'Goal Mode',
    'start_surah': 'Start Surah',
    'start_ayah': 'Start Ayah',
    'target_surah': 'Target Surah',
    'target_ayah': 'Target Ayah',
    'start_juz': 'Start Juz',
    'target_juz': 'Target Juz',
    'goal_title': 'Set Reading Goal',
    'goal_completed': 'Congratulations! Goal Completed',
    'daily_streak': 'Daily Reading Streak',
    'streak_count': '{days} Days Streak',
    'profile': 'Profile',
    'sign_in': 'Sign In',
    'sign_out': 'Sign Out',
    'email': 'Email',
    'password': 'Password',
    'no_notes': 'No reflections for this surah',
    'quran_only': 'Arabic Only',
    'translation_only': 'Translation Only',
    'quran_translation': 'Arabic & Translation',
    'choose_surah': 'Choose Surah',
    'delete_confirm': 'Are you sure you want to delete this?',
    'yes': 'Yes',
    'no': 'No',
    'delete': 'Delete',
    'completed_ayats': 'Completed Ayats',
    'total_progress': 'Total Progress',
    'juz_mode': 'By Juz',
    'surah_mode': 'By Surah',
    'ayah_mode': 'By Ayah',
    'custom_mode': 'Custom',
    'mushaf_meaningful_desc':
        'Increase intimacy with the Quran by reading it with meaning, reflecting verse by verse, InshaAllah.',
    'mushaf_read_desc':
        'Read the Quran from the Mushaf page for familiarity and memorization.',
    'delete_goal_title': 'Delete Reading Plan?',
    'delete_goal_confirm': 'Do you want to delete this reading plan?',
    'all_notes': 'All',
    'notes_count': '({count} reflections)',
    'qcf_v1': 'QCF V1 (Standard Mushaf)',
    'qcf_v2': 'QCF V2 (Expanded Mushaf)',
    'thai_v3': 'Arab Alumni Association (Detailed)',
    'thai_v2': 'Legacy Thai Translation',
    'english': 'English (Sahih International)',
    'qcf_tajweed': 'QCF Tajweed V4',
    'qcf_package': 'QCF Package',
    'download_more': 'Download More',
    'at_least_one_active': 'At least one translation must be active.',
    'reading_progress': 'Your reading progress',
    'see_more': 'See more',
    'recent_verse': 'Recent Verse-by-Verse',
    'recent_mushaf': 'Recent Mushaf Pages',
    'saved_verses': 'Saved Verses',
    'saved_mushaf': 'Saved Mushaf Pages',
    'no_saved_verses': 'No saved verses yet.',
    'ayah_number': 'Ayah {number}',
    'surah_number': 'Surah {number}',
    'ayat_count': '{count} ayat',
    'no_results_for': 'No results found for "{query}"',
    'create_goal': 'Create Reading Goal',
    'edit_goal': 'Edit Reading Goal',
    'goal_name': 'Goal name',
    'plan_type': 'Plan type',
    'reset_progress': 'Reset Progress to Start',
    'goal_progress_reset': 'Goal progress reset.',
    'enter_goal_name': 'Enter a goal name first.',
    'goal': 'Goal',
    'switch_home_tab_create_goal':
        'Please switch to the main Home tab to create a goal for now.',
    'please_enter_goal_name': 'Please enter a goal name first.',
    'juz_count': '{count} juz',
    'page_count': '{count} pages',
    'create': 'Create',
    'end_must_be_after_start': 'End position must be after the start.',
    'edit_name': 'Edit Name',
    'name': 'Name',
    'please_enter_name': 'Please enter a name',
    'name_updated_successfully': 'Name updated successfully',
    'error_occurred': 'An error occurred: {error}',
  },
};

extension LocalizationExtension on BuildContext {
  String tr(String key, {Map<String, String>? args}) {
    final settings = Provider.of<SettingsProvider>(this, listen: false);
    final lang = settings.languageCode;
    var value =
        _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}
