// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCC6REcib7qJBhZxsMLVJ_4hKRYKEapQ',
    appId: '1:913097538260:web:b97ff6ba63ae5527455941',
    messagingSenderId: '913097538260',
    projectId: 'iqra-quran-project',
    authDomain: 'iqra-quran-project.firebaseapp.com',
    storageBucket: 'iqra-quran-project.firebasestorage.app',
    measurementId: 'G-GFT457S3ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxOSlkB9rxVRNWUHj5JjPtHPnLIwfeog',
    appId: '1:913097538260:android:4a97f7445c47085b455941',
    messagingSenderId: '913097538260',
    projectId: 'iqra-quran-project',
    storageBucket: 'iqra-quran-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGuKbyfVCGixd4zMjOGLrieMicqRIGRps',
    appId: '1:913097538260:ios:bb56840f5ed2917a455941',
    messagingSenderId: '913097538260',
    projectId: 'iqra-quran-project',
    storageBucket: 'iqra-quran-project.firebasestorage.app',
    iosBundleId: 'com.abuzayd.iqra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGuKbyfVCGixd4zMjOGLrieMicqRIGRps',
    appId: '1:913097538260:ios:e5b2e0e53b30d422455941',
    messagingSenderId: '913097538260',
    projectId: 'iqra-quran-project',
    storageBucket: 'iqra-quran-project.firebasestorage.app',
    iosBundleId: 'com.example.thaiQuranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKCC6REcib7qJBhZxsMLVJ_4hKRYKEapQ',
    appId: '1:913097538260:web:1b33c07edd979498455941',
    messagingSenderId: '913097538260',
    projectId: 'iqra-quran-project',
    authDomain: 'iqra-quran-project.firebaseapp.com',
    storageBucket: 'iqra-quran-project.firebasestorage.app',
    measurementId: 'G-MLE3QDDFK0',
  );
}
